app = "oraculo"  # Substitua pelo nome da sua aplicação no Fly.io

[build]
  image = "python:3.11-slim"  # Usando a versão mais recente do Python

[env]
  # Defina as variáveis de ambiente, se necessário
  PORT = "8080"  # Porta padrão para Streamlit no Fly.io

[[services]]
  http_checks = []
  internal_port = 8080  # Porta que o Streamlit escuta
  processes = ["app"]
  protocol = "tcp"

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[deploy]
  release_command = "pip install streamlit python-dotenv requests cohere"  # Instala as dependências listadas no setup.py

[processes]
  app = "streamlit run cohere_integration.py --server.port 8080 --server.headless true"
