# fly.toml app configuration file generated for oraculo-quiet-water-3435 on 2024-10-09T00:53:03Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'oraculo-quiet-water-3435'
primary_region = 'gig'

[build]
  # Comando para instalar as dependências
  commands = [
    "pip install -r requirements.txt"
  ]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[processes]
  app = "python3.12 -m streamlit run cohere_integration.py --server.port 8080 --server.headless true --server.address 0.0.0.0"

[env]
  # Define a versão do Python a ser utilizada
  PYTHON_VERSION = "3.12.6"
