# fly.toml app configuration file generated for oraculo-quiet-water-3435 on 2024-10-09T00:53:03Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'oraculo-quiet-water-3435'
primary_region = 'gig'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[processes]
  app = "streamlit run cohere_integration.py --server.port 8080 --server.headless true"
